issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-demo/images-bite-back-talk:ref:refs/heads/main

permissions:
  checks: write
  contents: write
  issues: write
  members: read
  pull_requests: write
  statuses: write
  workflows: write
