name: Simple Build

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    permissions: # needed for signing and attestations
     id-token: write # write seems weird, but it is correct per docs
     attestations: write
     contents: read
     packages: write

    runs-on: ubuntu-latest

    steps:
      - 
        name: Install Cosign
        uses: chainguard-actions/cosign-installer@3d4272fbfb966daf6ef8207d58530a6aa228bd45 # v4.1.1
      -
        name: Set up Docker Buildx
        uses: chainguard-actions/setup-buildx-action@3acf63f460233367fa40633cd9d0047eec92e34c # v4.0.0
      -
        name: Login to GitHub Container Registry
        uses: chainguard-actions/login-action@c394a9b213683a599664fae2e8195c19b375a638 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: chainguard-actions/metadata-action@e880168b5f1f5c49fc62c706f78ee3d2eb03ce69 # v6.0.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-simple
          labels: |
            org.opencontainers.image.description=Demo Simple Build
      -
        name: Build and push
        id: build
        uses: chainguard-actions/docker-build-push-action@22423ee40e2c39461fa91af4ca8aaadb5e20b563 # v7.0.0
        with:
          file: Dockerfile
          platforms: linux/amd64
          push: true
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Attest
        uses: chainguard-actions/attest-build-provenance@c52790f45e81e8ce3d44fd64d15e089cdac2d60e # v4.1.0
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-simple
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
      - 
        name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
