# Copyright 2026 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Zizmor

on:
  pull_request:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      actions: read # Required by codeql-action/upload-sarif to get workflow run info
      contents: read # Clone the repository
      security-events: write # Upload SARIF results to Code Scanning
    steps:
      - uses: chainguard-actions/harden-runner@e20806565d40fd3200c720c50b4890d29916277c # v2.16.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            pkg-containers.githubusercontent.com:443
            ghcr.io

      - name: Check out code
        uses: chainguard-actions/checkout@d1f1061cdaee56aa3a3bc3deb86b67b1db772dd6 # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: chainguard-actions/zizmor-action@310f7d6f353a8d9bf06c667f33b1bafef2c5dd29 # v0.5.2
